"use client";

import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import type { ChallengeSolverCommandBarT } from "@/components/challenges/ChallengeSolverCommandBarTypes";

export interface ChallengeSolverOrderPuzzleBlockProps {
  puzzleOrder: string[];
  userAnswer: string;
  onUserAnswerChange: (value: string) => void;
  t: ChallengeSolverCommandBarT;
}

export function ChallengeSolverOrderPuzzleBlock({
  puzzleOrder,
  userAnswer,
  onUserAnswerChange,
  t,
}: ChallengeSolverOrderPuzzleBlockProps) {
  return (
    <div className="space-y-3">
      <div className="p-4 bg-muted/50 rounded-xl border border-border">
        <p className="text-sm font-medium text-foreground mb-2">{t("currentOrder")}</p>
        <div className="flex flex-wrap gap-2">
          {puzzleOrder.map((item, index) => (
            <Badge key={index} variant="outline" className="text-sm">
              {index + 1}. {item}
            </Badge>
          ))}
        </div>
      </div>
      <p className="text-xs text-muted-foreground">{t("reorderHint")}</p>
      <Input
        type="text"
        value={userAnswer}
        onChange={(e) => onUserAnswerChange(e.target.value)}
        placeholder={t("orderAutoGenerated")}
        className="opacity-50"
        disabled
        aria-label={t("puzzleAnswerLabel")}
      />
    </div>
  );
}
